# Generated by Django 5.2.8 on 2026-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_equipo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
    ]
