# Generated by Django 6.0.2 on 2026-02-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_jugador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
