# Generated by Django 5.2.8 on 2026-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_alter_jugador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
