# Generated by Django 5.2.8 on 2026-03-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_alter_equipo_id'),
        ('jugadores', '0004_alter_jugador_foto_alter_jugador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metros, ej: 1.80', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='goles_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jugador',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kg, ej: 75.5', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='HistorialClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(default=0)),
                ('temporadas', models.CharField(help_text='Ej: 2020-2022', max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_jugadores', to='equipos.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='jugadores.jugador')),
            ],
        ),
    ]
