# Generated by Django 6.0.2 on 2026-03-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0005_jugador_altura_jugador_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='goles_totales',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='peso',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='HistorialClub',
        ),
    ]
